# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9960be4326af9259f36c4d49702639dea00b4fc2039610ebd94d1bc0bc45423d295b2efc6894a8dfc9fd57dfa6763ae5f8d0b041c9720356b06e6c9aa0f2de

test:
  secret_key_base: aa3c19b10654d6f71eaebacaa004954bf0aafe9d41f78caf960d4606edd246e94e7c346afca84173efbefc180556b7fbfad5b1376a044492967234ce30f1897f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
